name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel twine
          pip install -r requirements.txt

      - name: Build the wheel
        run: python setup.py sdist bdist_wheel

      #- name: Publish to Test PyPI (dev version)
      #  if: contains(github.ref_name, 'dev')
      #  run: twine upload --repository testpypi dist/*.whl --username __token__ --password ${{ secrets.TEST_PYPI_API_TOKEN }}

      #- name: Publish to PyPI (release version)
      #  if: ${{ ! contains(github.ref_name, 'dev') }}
      #  run: twine upload dist/*.whl --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

      - name: Create release
        if: ${{ ! contains(github.ref_name, 'dev') }}
        uses: softprops/action-gh-release@v1
        with:
          name: ColabKit ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
